---
title: "Apresentação RMarkdown"
author: "marcos"
date: "02/02/2023"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

1.1 - Importando as bibliotecas

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(tidyverse)
library(RSelenium)
library(netstat)
library(readxl)
library(writexl)

```

1.2 - Criando uma conexção com o portal Firefox

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
rs_driver_object <- rsDriver(browser = "firefox",
                             chromever = NULL,
                             verbose = FALSE,
                             port = free_port())
```

1.3 - criando uma conexão cleinte

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
remDr <-  rs_driver_object$client
```

1.4 objeto site

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
site_sancoes <- "https://www.bec.sp.gov.br/sancoes_ui/aspx/consultaadministrativafornecedor.aspx"
```

1.5 carregando banco de dados

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
cnpj_list <- read_excel("banco_cnpj.xlsx")
```

1.6 função para

```{r message=FALSE, warning=FALSE, paged.print=FALSE}

funcao_sancoes <- function(cnpj_empresas){
  remDr$navigate(site_sancoes)
  remDr$findElement(using= "id", "txtCNPJCPF")$sendKeysToElement(c(cnpj_empresas, key = "enter"))
  Sys.sleep(2)
  css_obj <- 'table.styled:nth-child(3) > tbody:nth-child(1)'
  if(substr(remDr$findElement(using='css selector', css_obj)$getElementText(), 74, 102)=="Não foram encontradas sanções"){
    print("ok")
  }else {print("pendencia")}
  }
```

1.7 Looping para carraagar os dados

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
write_xlsx(cbind(cnpj_list,sapply(cnpj_list$cnpj, FUN = funcao_sancoes)), "resultado e-sancoes.xlsx")
```
